kind: Kustomization
resources:
  - database
  - exoplanets
secretGenerator:
  - name: db-secrets
    literals:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=database
      - DB_ADMIN_PASSWORD=postgres
configMapGenerator:
  - name: db-config
    literals:
      - DB_HOST=database
      - DB_PORT=5432