apiVersion: apps/v1
kind: Deployment
metadata:
  name: ll-withprobes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: long-load-delay
  template:
    metadata:
      labels:
        app: long-load-delay
    spec:
      containers:
        - image: quay.io/redhattraining/long-load:v1
          name: long-load-delay
          resources:
            requests:
              memory: 20Mi # you can play with this value
            limits:
              memory: 35Mi # with this value, pods will crash
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            failureThreshold: 6
            periodSeconds: 5
            httpGet:
              path: /health
              port: 3000
      restartPolicy: Always


# Various endpoints available in this app
  # /ping
  # /health
  # /leak
  # /unleak
  # /togglesick
  # /hiccup
  # /destruct