# v3 is also about combing deployment, service, route
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ll-withprobes
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: long-load-delay
      template:
        metadata:
          labels:
            app: long-load-delay
        spec:
          containers:
            - image: quay.io/redhattraining/long-load:v1
              name: long-load-delay
              resources:
                requests:
                  memory: 20Mi # you can play with this value
                  cpu: 25m
                limits:
                  memory: 250Mi # you can use less than 60Mi value
                  cpu: 100m
              imagePullPolicy: Always
              securityContext:
                allowPrivilegeEscalation: false
              livenessProbe:
                failureThreshold: 6
                periodSeconds: 5
                httpGet:
                  path: /health
                  port: 3000
          restartPolicy: Always
  - apiVersion: v1
    metadata:
      name: ll-withprobes
    kind: Service
    spec:
      ports:
        - port: 3000
          protocol: TCP
          targetPort: 3000
      selector:
        app: long-load-delay
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ll-withprobes
    spec:
      port:
        targetPort: 3000
      to:
        kind: Service
        name: ll-withprobes






# Various endpoints available in this app
  # /ping
  # /health
  # /leak
  # /unleak
  # /togglesick
  # /hiccup
  # /destruct