apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbserver
spec:
  selector:
    matchLabels:
      app: database
  replicas: 2
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: dbserver
          image: registry.redhat.io/rhel9/mysql-80
          ports:
            - name: database
              containerPort: 3306
          env:
            - name: MYSQL_USER
              value: "redhat"
            - name: MYSQL_PASSWORD
              value: "redhat123"
            - name: MYSQL_DATABASE
              value: sakila
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: crc-csi-hostpath-provisioner
        resources:
          requests:
            storage: 1Gi