apiVersion: v1
kind: Pod
metadata:
  name: secret-example-pod
spec:
  containers:
    - name: secret-pod
      image: pathToTheImage
      command: ["/bin/sh", "-c", "export"]
  env:
    - name: Test_Secret
      valueFrom:
        secretKeyRef:
          name: test-secret # value of the secret username (key)
          key: username # corresponding secret for the username (key)