---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"httpd24","creationTimestamp":null,"labels":{"app":"httpd24"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"httpd24"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"httpd24"}},"spec":{"containers":[{"name":"httpd-24","image":"registry.redhat.io/ubi9/httpd-24","resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: null
  labels:
    app: httpd24
  name: httpd24
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd24
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd24
    spec:
      containers:
      - image: registry.redhat.io/ubi9/httpd-24
        name: httpd-24
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
status: {}
---
apiVersion: v1
metadata:
  name: httpd24-service
kind: Service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpd24
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: httpd24-route
spec:
  host: myhttpd.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: httpd24-service